"""add academic_year

Revision ID: 894cd0392a71
Revises: ab2e5d7e05e8
Create Date: 2026-02-13 12:00:43.984909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894cd0392a71'
down_revision: Union[str, None] = 'ab2e5d7e05e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note that the Real to Float is meant to better reflect the model
    op.alter_column('accelerate', 'participation_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('accelerate_course_progress', 'pathway_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('missing_attendance', 'peardeck_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    op.alter_column('student_attendance', 'peardeck_score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)
    # New column
    op.add_column('students', sa.Column('academic_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'academic_year')
    op.alter_column('student_attendance', 'peardeck_score',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('missing_attendance', 'peardeck_score',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accelerate_course_progress', 'pathway_score',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accelerate', 'participation_score',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
