"""Add student_count to attendance table and remove session_score and attended_minutes

Revision ID: c0025f85a371
Revises: 234eb1d89dec
Create Date: 2025-09-11 01:21:44.667601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0025f85a371'
down_revision: Union[str, None] = '234eb1d89dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('student_count', sa.Integer(), nullable=True))
    op.add_column('missing_attendance', sa.Column('full_attendance', sa.Boolean(), server_default=sa.false()))
    op.drop_column('missing_attendance', 'attended_minutes')
    op.add_column('student_attendance', sa.Column('full_attendance', sa.Boolean(), server_default=sa.false()))
    op.drop_column('student_attendance', 'attended_minutes')
    op.drop_column('student_attendance', 'session_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_attendance', sa.Column('session_score', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('student_attendance', sa.Column('attended_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('student_attendance', 'full_attendance')
    op.add_column('missing_attendance', sa.Column('attended_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('missing_attendance', 'full_attendance')
    op.drop_column('attendance', 'student_count')
    # ### end Alembic commands ###
