name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CTI_POSTGRES_URL: ${{ secrets.CTI_POSTGRES_URL }}
      CTI_MONGO_URL: ${{ secrets.CTI_MONGO_URL }}
      CTI_ACCESS_TOKEN: ${{ secrets.CTI_ACCESS_TOKEN }}
      APP_ENV: ${{ secrets.APP_ENV }}
      CTI_SYS_ADMIN_KEY: ${{ secrets.CTI_SYS_ADMIN_KEY }}
      COURSE_ID_UNTERVIEW: ${{ secrets.COURSE_ID_UNTERVIEW }}
      UNTERVIEW_SIS_COURSE_ID: ${{ secrets.UNTERVIEW_SIS_COURSE_ID }}
      CUR_UNTERVIEW_SIS_SECTION_ID: ${{ secrets.CUR_UNTERVIEW_SIS_SECTION_ID }}
      CUR_UNTERVIEW_SECTION_ID: ${{ secrets.CUR_UNTERVIEW_SECTION_ID }}
      COURSE_ID_101: ${{ secrets.COURSE_ID_101 }}
      COMMITMENT_QUIZ_ID: ${{ secrets.COMMITMENT_QUIZ_ID }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_SENDER: ${{ secrets.SENDGRID_SENDER }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: pytest -v -m "not integration"
